[project]
name = "vggt-streamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.39.4",
    "einops>=0.8.1",
    "torch==2.3.1+cu121",
    "torchvision==0.18.1+cu121",
    "vggt",
]

[tool.uv.sources]
vggt = { git = "https://github.com/facebookresearch/vggt.git" }

[tool.uv]
find-links = ["https://download.pytorch.org/whl/torch_stable.html"]
